version: "3.9"
services:
  app:
    image: boombox
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      # Prisma
      - DATABASE_URL=file:./db.sqlite

      # Authentication (Logto)
      # The URL to the Logto server
      - LOGTO_ENDPOINT=http://localhost:3001
      # The URL to the app
      - LOGTO_BASE_URL=http://localhost:3000
      # A 32 digit secret. Please randomize this
      - LOGTO_COOKIE_SECRET=kb8qUqc7hdObRuFEET6ZIOGDj7EUR2yP
      # Get these from your dashboard, make sure the app is "Traditional Web"
      - LOGTO_APP_ID=eY4buTh3wzGbOLgMEkzxG
      - LOGTO_APP_SECRET=GJs06YAqxXO11Don5eHHi

      # Maloja
      - MALOJA_URL=http://localhost:42010
      - MALOJA_API_KEY=IZqYmJgEt4E1YDk1Eb3PnJbgFxGW3jLowuPkELP121JaLJlq1uELBiekzehch0ZL
  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:prerelease
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@postgres:5432
      - ENDPOINT
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5