version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./data/:/app/data
      - ./data/images:/app/data/images
    environment:
      # Authentication (Logto)
      # The URL to the Logto server
      - LOGTO_ENDPOINT=http://localhost:3001
      # The URL to the app
      - LOGTO_BASE_URL=http://localhost:3000
      # A 32 digit secret. Please randomize this
      - LOGTO_COOKIE_SECRET=nyanyanyanyanyanyanyanyanyanyany
      # Get these from your dashboard, make sure the app is "Traditional Web"
      - LOGTO_APP_ID=appid
      - LOGTO_APP_SECRET=appsecret

      # Maloja
      - MALOJA_URL=http://localhost:42010
      - MALOJA_API_KEY=nyanyanyanyanyanyanyanyanyanyanyanyanyanyanyanyanyanyanyanyanyan

      # Boombox
      # URL to database
      - DATABASE_URL=file:/app/data/db.sqlite
      # Whether to require admin authentication for the /api/maloja-redirect (/maloja redirects to that) route.
      # Optional, defaults to false.
      # BOOMBOX_MALOJA_REQUIRE_AUTH=false
  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:prerelease
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@postgres:5432/logto
      - ENDPOINT
  postgres:
    image: postgres:14-alpine
    user: postgres
      - ./other-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  maloja:
    image: krateng/maloja
    ports:
      - 42010:42010
    volumes:
      - ./other-data/maloja:/mljdata
    environment:
      - MALOJA_DATA_DIRECTORY=/mljdata
      - MALOJA_FORCE_PASSWORD=testpass